spring:
  application:
    name: kubemq-example-queries-consumer-group
  main:
    web-application-type: none

kubemq:
  address: ${KUBEMQ_ADDRESS:localhost:50000}
  client-id: spring-queries-consumer-group
