spring:
  application:
    name: kubemq-example-events-multiple-subscribers
  main:
    web-application-type: none

kubemq:
  address: ${KUBEMQ_ADDRESS:localhost:50000}
  client-id: spring-events-multiple-subscribers
