spring:
  application:
    name: kubemq-example-management-purge-queue
  main:
    web-application-type: none

kubemq:
  address: ${KUBEMQ_ADDRESS:localhost:50000}
  client-id: spring-management-purge-queue
