spring:
  application:
    name: kubemq-example-error-handling-graceful-shutdown
  main:
    web-application-type: none

kubemq:
  address: ${KUBEMQ_ADDRESS:localhost:50000}
  client-id: spring-error-handling-graceful-shutdown
