spring:
  application:
    name: kubemq-example-events-basic-pubsub
  main:
    web-application-type: none

kubemq:
  address: ${KUBEMQ_ADDRESS:localhost:50000}
  client-id: spring-events-basic-pubsub
